//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class demoMain:public drogon::DrTemplate<demoMain>
{
public:
	demoMain(){};
	virtual ~demoMain(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
