//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class model_json:public drogon::DrTemplate<model_json>
{
public:
	model_json(){};
	virtual ~model_json(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
