//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class plugin_cc:public drogon::DrTemplate<plugin_cc>
{
public:
	plugin_cc(){};
	virtual ~plugin_cc(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
