//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class restful_controller_custom_h:public drogon::DrTemplate<restful_controller_custom_h>
{
public:
	restful_controller_custom_h(){};
	virtual ~restful_controller_custom_h(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
