//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class TestView:public drogon::DrTemplate<TestView>
{
public:
	TestView(){};
	virtual ~TestView(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
