//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "TestView.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>

#include <iostream>

using namespace drogon;
std::string TestView::genText(const DrTemplateData& TestView_view_data)
{
	drogon::OStringStream TestView_tmp_stream;
	std::string layoutName{""};
std::cout<<"this is a Http backend rendering Test"<<std::endl;
	TestView_tmp_stream << "<!DOCTYPE html>\n";
	TestView_tmp_stream << "<html>\n";
 std::string title=TestView_view_data.get<std::string>("title");
	TestView_tmp_stream << "<head>\n";
	TestView_tmp_stream << "    <meta charset=\"UTF-8\">\n";
	TestView_tmp_stream << "    <title>";
 TestView_tmp_stream<<title;
	TestView_tmp_stream << "</title>\n";
	TestView_tmp_stream << "</head>\n";
	TestView_tmp_stream << "<body>\n";
	TestView_tmp_stream << "<footer>\n";
	TestView_tmp_stream << "    <span>CopyRight@2017 All Rights Reserved</span>\n";
	TestView_tmp_stream << "</footer>\n";
	TestView_tmp_stream << "</body>\n";
	TestView_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(TestView_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = TestView_view_data;
auto str = std::move(TestView_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
