/**
 *
 *  @file orm_reflection_test.cc
 *  @author Leonardo Moreira
 *  @brief Tests for the experimental C++26 reflection based ORM mapper.
 *
 *  Copyright 2018, An Tao.  All rights reserved.
 *  https://github.com/drogonframework/drogon
 *  Use of this source code is governed by a MIT license
 *  that can be found in the License file.
 *
 */

#include <drogon/config.h>
#include <drogon/orm/ReflectiveMapper.h>

#include <chrono>
#include <condition_variable>
#include <cstddef>
#include <cstdint>
#include <exception>
#include <iostream>
#include <limits>
#include <memory>
#include <meta>
#include <mutex>
#include <optional>
#include <source_location>
#include <stdexcept>
#include <string>
#include <string_view>
#include <type_traits>
#include <utility>
#include <vector>

namespace
{
namespace reflection = drogon::orm::reflection;

// clang-format currently treats reflection annotations as ordinary attributes.
// clang-format off
struct [[=reflection::Table{"main.reflective_users"}]] ReflectedUser
{
    [[=reflection::PrimaryKey{}, =reflection::AutoGenerated{}]]
    std::optional<std::uint64_t> id;

    [[=reflection::Column{"display_name"}]]
    std::string name;

    std::optional<std::string> email;
    std::int32_t score{};

    [[=reflection::Ignore{}]]
    std::string transientState;
};

struct [[=reflection::Table{"narrow_generated_keys"}]] NarrowGeneratedKey
{
    [[=reflection::PrimaryKey{}, =reflection::AutoGenerated{}]]
    std::uint8_t id{};
};

// clang-format on

using UserMapper = drogon::orm::ReflectiveMapper<ReflectedUser>;
namespace reflectionInternal = drogon::orm::reflection::internal;

consteval bool reflectedUserMetadataIsStable()
{
    using namespace std::meta;

    const auto members =
        nonstatic_data_members_of(^^ReflectedUser,
                                  access_context::unprivileged());
    return annotations_of(^^ReflectedUser).size() == 1 && members.size() == 5 &&
           identifier_of(members[0]) == "id" &&
           identifier_of(members[1]) == "name" &&
           identifier_of(members[2]) == "email" &&
           identifier_of(members[3]) == "score" &&
           identifier_of(members[4]) == "transientState" &&
           annotations_of(members[0]).size() == 2 &&
           annotations_of(members[1]).size() == 1 &&
           annotations_of(members[2]).empty() &&
           annotations_of(members[3]).empty() &&
           annotations_of(members[4]).size() == 1;
}

static_assert(std::is_aggregate_v<ReflectedUser>);
static_assert(reflectedUserMetadataIsStable());
static_assert(std::is_same_v<UserMapper::PrimaryKeyType, std::uint64_t>);

using reflectionInternal::Dialect;

static_assert(
    std::string_view{
        reflectionInternal::selectSql<ReflectedUser, Dialect::PostgreSQL>} ==
    "select \"id\",\"display_name\",\"email\",\"score\" from "
    "\"main\".\"reflective_users\"");
static_assert(
    std::string_view{
        reflectionInternal::selectSql<ReflectedUser, Dialect::Mysql>} ==
    "select `id`,`display_name`,`email`,`score` from "
    "`main`.`reflective_users`");
static_assert(
    std::string_view{
        reflectionInternal::selectSql<ReflectedUser, Dialect::Sqlite3>} ==
    "select \"id\",\"display_name\",\"email\",\"score\" from "
    "\"main\".\"reflective_users\"");

static_assert(
    std::string_view{
        reflectionInternal::findByPrimaryKeySql<ReflectedUser,
                                                Dialect::PostgreSQL>} ==
    "select \"id\",\"display_name\",\"email\",\"score\" from "
    "\"main\".\"reflective_users\" where \"id\" = $1");
static_assert(std::string_view{
                  reflectionInternal::findByPrimaryKeySql<ReflectedUser,
                                                          Dialect::Mysql>} ==
              "select `id`,`display_name`,`email`,`score` from "
              "`main`.`reflective_users` where `id` = ?");
static_assert(std::string_view{
                  reflectionInternal::findByPrimaryKeySql<ReflectedUser,
                                                          Dialect::Sqlite3>} ==
              "select \"id\",\"display_name\",\"email\",\"score\" from "
              "\"main\".\"reflective_users\" where \"id\" = ?");

static_assert(
    std::string_view{
        reflectionInternal::countSql<ReflectedUser, Dialect::PostgreSQL>} ==
    "select count(*) from \"main\".\"reflective_users\"");
static_assert(
    std::string_view{
        reflectionInternal::countSql<ReflectedUser, Dialect::Mysql>} ==
    "select count(*) from `main`.`reflective_users`");
static_assert(
    std::string_view{
        reflectionInternal::countSql<ReflectedUser, Dialect::Sqlite3>} ==
    "select count(*) from \"main\".\"reflective_users\"");

static_assert(
    std::string_view{
        reflectionInternal::insertSql<ReflectedUser, Dialect::PostgreSQL>} ==
    "insert into \"main\".\"reflective_users\" "
    "(\"display_name\",\"email\",\"score\") values ($1,$2,$3) returning "
    "\"id\",\"display_name\",\"email\",\"score\"");
static_assert(
    std::string_view{
        reflectionInternal::insertSql<ReflectedUser, Dialect::Mysql>} ==
    "insert into `main`.`reflective_users` "
    "(`display_name`,`email`,`score`) values (?,?,?)");
static_assert(
    std::string_view{
        reflectionInternal::insertSql<ReflectedUser, Dialect::Sqlite3>} ==
    "insert into \"main\".\"reflective_users\" "
    "(\"display_name\",\"email\",\"score\") values (?,?,?)");

static_assert(
    std::string_view{
        reflectionInternal::updateSql<ReflectedUser, Dialect::PostgreSQL>} ==
    "update \"main\".\"reflective_users\" set \"display_name\" = "
    "$1,\"email\" = $2,\"score\" = $3 where \"id\" = $4");
static_assert(
    std::string_view{
        reflectionInternal::updateSql<ReflectedUser, Dialect::Mysql>} ==
    "update `main`.`reflective_users` set `display_name` = ?,`email` = "
    "?,`score` = ? where `id` = ?");
static_assert(
    std::string_view{
        reflectionInternal::updateSql<ReflectedUser, Dialect::Sqlite3>} ==
    "update \"main\".\"reflective_users\" set \"display_name\" = "
    "?,\"email\" = ?,\"score\" = ? where \"id\" = ?");

static_assert(
    std::string_view{
        reflectionInternal::deleteSql<ReflectedUser, Dialect::PostgreSQL>} ==
    "delete from \"main\".\"reflective_users\" where \"id\" = $1");
static_assert(
    std::string_view{
        reflectionInternal::deleteSql<ReflectedUser, Dialect::Mysql>} ==
    "delete from `main`.`reflective_users` where `id` = ?");
static_assert(
    std::string_view{
        reflectionInternal::deleteSql<ReflectedUser, Dialect::Sqlite3>} ==
    "delete from \"main\".\"reflective_users\" where \"id\" = ?");

#if USE_SQLITE3
drogon::orm::DbClientPtr makeClient()
{
    auto client =
        drogon::orm::DbClient::newSqlite3Client("filename=:memory:", 1);
    client->execSqlSync(
        "CREATE TABLE reflective_users ("
        "id INTEGER PRIMARY KEY AUTOINCREMENT,"
        "display_name TEXT,"
        "email TEXT,"
        "score INTEGER NOT NULL"
        ")");
    return client;
}

ReflectedUser makeUser(std::string name,
                       std::optional<std::string> email,
                       std::int32_t score)
{
    ReflectedUser user;
    user.name = std::move(name);
    user.email = std::move(email);
    user.score = score;
    user.transientState = "must not be persisted";
    return user;
}

void testCheck(bool condition,
               std::string_view expression,
               std::source_location location = std::source_location::current())
{
    if (!condition)
    {
        throw std::runtime_error(std::string{location.file_name()} + ":" +
                                 std::to_string(location.line()) +
                                 ": check failed: " + std::string{expression});
    }
}

template <typename Exception, typename Callable>
void testThrowsAs(
    Callable &&callable,
    std::string_view expression,
    std::source_location location = std::source_location::current())
{
    try
    {
        std::forward<Callable>(callable)();
    }
    catch (const Exception &)
    {
        return;
    }
    catch (const std::exception &error)
    {
        throw std::runtime_error(
            std::string{location.file_name()} + ":" +
            std::to_string(location.line()) + ": expected exception from " +
            std::string{expression} + ", got: " + error.what());
    }
    catch (...)
    {
        throw std::runtime_error(std::string{location.file_name()} + ":" +
                                 std::to_string(location.line()) +
                                 ": expected a different exception type from " +
                                 std::string{expression});
    }
    throw std::runtime_error(std::string{location.file_name()} + ":" +
                             std::to_string(location.line()) +
                             ": expected an exception from " +
                             std::string{expression});
}

class AsyncGroup
{
  public:
    using Ticket = std::size_t;

    explicit AsyncGroup(std::size_t expected)
        : completed_(expected, false), remaining_(expected)
    {
    }

    void complete(Ticket ticket) noexcept
    {
        finish(ticket, nullptr);
    }

    void fail(Ticket ticket, std::exception_ptr error) noexcept
    {
        finish(ticket, std::move(error));
    }

    void fail(Ticket ticket, std::string message) noexcept
    {
        try
        {
            throw std::runtime_error(std::move(message));
        }
        catch (...)
        {
            fail(ticket, std::current_exception());
        }
    }

    void wait()
    {
        std::unique_lock lock(mutex_);
        if (!condition_.wait_for(lock, std::chrono::seconds{15}, [this] {
                return remaining_ == 0;
            }))
        {
            throw std::runtime_error(
                "Timed out waiting for reflective ORM callbacks");
        }
        const auto error = error_;
        const auto invalidCompletion = invalidCompletion_;
        lock.unlock();
        if (error)
        {
            std::rethrow_exception(error);
        }
        if (invalidCompletion)
        {
            throw std::runtime_error(
                "A reflective ORM callback completed more than once");
        }
    }

  private:
    void finish(Ticket ticket, std::exception_ptr error) noexcept
    {
        std::lock_guard lock(mutex_);
        if (error && !error_)
        {
            error_ = std::move(error);
        }
        if (ticket >= completed_.size() || completed_[ticket])
        {
            invalidCompletion_ = true;
        }
        else
        {
            completed_[ticket] = true;
            --remaining_;
        }
        condition_.notify_all();
    }

    std::mutex mutex_;
    std::condition_variable condition_;
    std::vector<bool> completed_;
    std::size_t remaining_;
    std::exception_ptr error_;
    bool invalidCompletion_{false};
};

template <typename Callable>
void guardAsync(const std::shared_ptr<AsyncGroup> &group,
                AsyncGroup::Ticket ticket,
                Callable &&callable) noexcept
{
    try
    {
        std::forward<Callable>(callable)();
    }
    catch (...)
    {
        group->fail(ticket, std::current_exception());
    }
}
#endif
}  // namespace

#define TEST_CHECK(expression) \
    testCheck(static_cast<bool>(expression), #expression)
#define TEST_THROWS_AS(expression, exception_type) \
    testThrowsAs<exception_type>([&] { (void)(expression); }, #expression)

#if USE_SQLITE3
void testReflectiveMapperSQLiteSync()
{
    using namespace drogon::orm;

    NarrowGeneratedKey narrowKey;
    reflectionInternal::assignGeneratedPrimaryKey(
        narrowKey, std::numeric_limits<std::uint8_t>::max());
    TEST_CHECK(narrowKey.id == std::numeric_limits<std::uint8_t>::max());
    TEST_THROWS_AS(reflectionInternal::assignGeneratedPrimaryKey(
                       narrowKey,
                       static_cast<std::uint64_t>(
                           std::numeric_limits<std::uint8_t>::max()) +
                           1),
                   RangeError);

    const auto client = makeClient();
    TEST_CHECK(client != nullptr);
    UserMapper mapper{client};

    TEST_CHECK(mapper.columnName<^^ReflectedUser::id>() == "\"id\"");
    TEST_CHECK(mapper.columnName<^^ReflectedUser::name>() ==
               "\"display_name\"");
    TEST_CHECK(mapper.columnName<^^ReflectedUser::email>() == "\"email\"");

    auto ada = makeUser("Ada", std::nullopt, 10);
    mapper.insert(ada);
    TEST_CHECK(ada.id.has_value());
    TEST_CHECK(*ada.id != 0);

    const auto byPrimaryKey = mapper.findByPrimaryKey(*ada.id);
    TEST_CHECK(byPrimaryKey.id == ada.id);
    TEST_CHECK(byPrimaryKey.name == "Ada");
    TEST_CHECK(!byPrimaryKey.email.has_value());
    TEST_CHECK(byPrimaryKey.score == 10);
    TEST_CHECK(byPrimaryKey.transientState.empty());

    const auto nameColumn = mapper.columnName<^^ReflectedUser::name>();
    const auto one = mapper.findOne(
        Criteria{nameColumn, CompareOperator::EQ, std::string{"Ada"}});
    TEST_CHECK(one.id == ada.id);

    const auto found = mapper.findBy(
        Criteria{nameColumn, CompareOperator::Like, std::string{"A%"}});
    TEST_CHECK(found.size() == 1);
    TEST_CHECK(found.front().name == "Ada");

    const auto all = mapper.findAll();
    TEST_CHECK(all.size() == 1);
    TEST_CHECK(all.front().id == ada.id);
    TEST_CHECK(mapper.count() == 1);
    TEST_CHECK(mapper.count(Criteria{nameColumn,
                                     CompareOperator::EQ,
                                     std::string{"nobody"}}) == 0);

    ada.name = "Ada Lovelace";
    ada.email = "ada@example.test";
    ada.score = 42;
    ada.transientState = "still not persisted";
    TEST_CHECK(mapper.update(ada) == 1);

    const auto updated = mapper.findByPrimaryKey(*ada.id);
    TEST_CHECK(updated.name == "Ada Lovelace");
    TEST_CHECK(updated.email.has_value());
    TEST_CHECK(*updated.email == "ada@example.test");
    TEST_CHECK(updated.score == 42);
    TEST_CHECK(updated.transientState.empty());

    auto noPrimaryKey = makeUser("No key", std::nullopt, 0);
    TEST_THROWS_AS(mapper.update(noPrimaryKey), UsageError);
    TEST_THROWS_AS(mapper.deleteOne(noPrimaryKey), UsageError);

    TEST_CHECK(mapper.deleteOne(ada) == 1);
    TEST_CHECK(mapper.count() == 0);

    auto grace = makeUser("Grace", "grace@example.test", 7);
    mapper.insert(grace);
    TEST_CHECK(grace.id.has_value());
    TEST_CHECK(mapper.deleteByPrimaryKey(*grace.id) == 1);
    TEST_CHECK(mapper.count() == 0);

    const auto badInsert = client->execSqlSync(
        "INSERT INTO reflective_users(display_name, email, score) "
        "VALUES(NULL, NULL, 1)");
    TEST_CHECK(badInsert.insertId() != 0);
    TEST_THROWS_AS(mapper.findByPrimaryKey(badInsert.insertId()),
                   ConversionError);
}

void testReflectiveMapperSQLiteCallbacks()
{
    using namespace drogon::orm;

    const auto client = makeClient();
    TEST_CHECK(client != nullptr);
    auto mapper = std::make_shared<UserMapper>(client);

    auto existing = makeUser("Existing", std::nullopt, 11);
    mapper->insert(existing);
    TEST_CHECK(existing.id.has_value());
    const auto existingId = *existing.id;
    const auto nameColumn = mapper->columnName<^^ReflectedUser::name>();

    constexpr std::size_t expectedCallbackChains = 7;
    constexpr AsyncGroup::Ticket missingKeyTicket = 0;
    constexpr AsyncGroup::Ticket primaryKeyTicket = 1;
    constexpr AsyncGroup::Ticket findOneTicket = 2;
    constexpr AsyncGroup::Ticket findByTicket = 3;
    constexpr AsyncGroup::Ticket findAllTicket = 4;
    constexpr AsyncGroup::Ticket countTicket = 5;
    constexpr AsyncGroup::Ticket mutationTicket = 6;
    auto group = std::make_shared<AsyncGroup>(expectedCallbackChains);
    const auto errorFor = [group](AsyncGroup::Ticket ticket) {
        return [group, ticket](const DrogonDbException &error) {
            group->fail(ticket,
                        std::string{"Unexpected reflective ORM error: "} +
                            error.base().what());
        };
    };

    mapper->findByPrimaryKey(
        std::uint64_t{999999},
        [group](ReflectedUser) {
            group->fail(missingKeyTicket,
                        "A missing primary key unexpectedly produced a row");
        },
        [group](const DrogonDbException &error) {
            guardAsync(group, missingKeyTicket, [&] {
                TEST_CHECK(dynamic_cast<const UnexpectedRows *>(&error) !=
                           nullptr);
                group->complete(missingKeyTicket);
            });
        });

    mapper->findByPrimaryKey(
        existingId,
        [group, existingId](ReflectedUser user) {
            guardAsync(group, primaryKeyTicket, [&] {
                TEST_CHECK(user.id == existingId);
                TEST_CHECK(user.name == "Existing");
                TEST_CHECK(!user.email.has_value());
                group->complete(primaryKeyTicket);
            });
        },
        errorFor(primaryKeyTicket));

    mapper->findOne(
        Criteria{nameColumn, CompareOperator::EQ, std::string{"Existing"}},
        [group, existingId](ReflectedUser user) {
            guardAsync(group, findOneTicket, [&] {
                TEST_CHECK(user.id == existingId);
                group->complete(findOneTicket);
            });
        },
        errorFor(findOneTicket));

    mapper->findBy(
        Criteria{nameColumn, CompareOperator::Like, std::string{"Exist%"}},
        [group, existingId](std::vector<ReflectedUser> users) {
            guardAsync(group, findByTicket, [&] {
                TEST_CHECK(users.size() == 1);
                TEST_CHECK(users.front().id == existingId);
                group->complete(findByTicket);
            });
        },
        errorFor(findByTicket));

    mapper->findAll(
        [group, existingId](std::vector<ReflectedUser> users) {
            guardAsync(group, findAllTicket, [&] {
                TEST_CHECK(users.size() == 1);
                TEST_CHECK(users.front().id == existingId);
                group->complete(findAllTicket);
            });
        },
        errorFor(findAllTicket));

    mapper->count(
        Criteria{nameColumn, CompareOperator::EQ, std::string{"Existing"}},
        [group](const std::size_t count) {
            guardAsync(group, countTicket, [&] {
                TEST_CHECK(count == 1);
                group->complete(countTicket);
            });
        },
        errorFor(countTicket));

    auto inserted = makeUser("Callback", "callback@example.test", 20);
    const auto mutationError = errorFor(mutationTicket);
    mapper->insert(
        inserted,
        [group, mapper, mutationError](ReflectedUser user) mutable {
            guardAsync(
                group, mutationTicket, [&] {
                    TEST_CHECK(user.id.has_value());
                    TEST_CHECK(user.name == "Callback");
                    TEST_CHECK(user.email == "callback@example.test");

                    user.name = "Callback updated";
                    user.email = std::nullopt;
                    user.score = 21;
                    mapper->update(
                        user,
                        [group, mapper, mutationError, user](
                            const std::size_t count) {
                            guardAsync(
                                group, mutationTicket, [&] {
                                    TEST_CHECK(count == 1);
                                    mapper
                                        ->findByPrimaryKey(
                                            *user.id,
                                            [group, mapper, mutationError](
                                                ReflectedUser updated) {
                                                guardAsync(group,
                                                           mutationTicket,
                                                           [&] {
                                                               TEST_CHECK(
                                                                   updated
                                                                       .name ==
                                                                   "Callback "
                                                                   "updated");
                                                               TEST_CHECK(
                                                                   !updated
                                                                        .email
                                                                        .has_value());
                                                               TEST_CHECK(
                                                                   updated
                                                                       .score ==
                                                                   21);
                                                               mapper
                                                                   ->deleteOne(
                                                                       updated,
                                                                       [group,
                                                                        mapper,
                                                                        mutationError](
                                                                           const std::size_t
                                                                               count) {
                                                                           guardAsync(group,
                                                                                      mutationTicket,
                                                                                      [&] {
                                                                                          TEST_CHECK(
                                                                                              count ==
                                                                                              1);

                                                                                          auto last = makeUser(
                                                                                              "Delete by key",
                                                                                              std::
                                                                                                  nullopt,
                                                                                              30);
                                                                                          mapper
                                                                                              ->insert(
                                                                                                  last,
                                                                                                  [group,
                                                                                                   mapper,
                                                                                                   mutationError](
                                                                                                      ReflectedUser
                                                                                                          insertedLast) {
                                                                                                      guardAsync(group, mutationTicket, [&] {
                                                                                                          TEST_CHECK(
                                                                                                              insertedLast
                                                                                                                  .id
                                                                                                                  .has_value());
                                                                                                          mapper
                                                                                                              ->deleteByPrimaryKey(
                                                                                                                  *insertedLast
                                                                                                                       .id,
                                                                                                                  [group](
                                                                                                                      const std::size_t
                                                                                                                          count) {
                                                                                                                      guardAsync(
                                                                                                                          group,
                                                                                                                          mutationTicket,
                                                                                                                          [&] {
                                                                                                                              TEST_CHECK(
                                                                                                                                  count ==
                                                                                                                                  1);
                                                                                                                              group
                                                                                                                                  ->complete(
                                                                                                                                      mutationTicket);
                                                                                                                          });
                                                                                                                  },
                                                                                                                  mutationError);
                                                                                                      });
                                                                                                  },
                                                                                                  mutationError);
                                                                                      });
                                                                       },
                                                                       mutationError);
                                                           });
                                            },
                                            mutationError);
                                });
                        },
                        mutationError);
                });
        },
        mutationError);

    group->wait();
}
#endif

int main()
{
#if USE_SQLITE3
    try
    {
        testReflectiveMapperSQLiteSync();
        testReflectiveMapperSQLiteCallbacks();
        std::cout << "Reflective ORM tests passed\n";
        return 0;
    }
    catch (const drogon::orm::DrogonDbException &error)
    {
        std::cerr << "Reflective ORM database test failed: "
                  << error.base().what() << '\n';
    }
    catch (const std::exception &error)
    {
        std::cerr << "Reflective ORM test failed: " << error.what() << '\n';
    }
    catch (...)
    {
        std::cerr << "Reflective ORM test failed with an unknown exception\n";
    }
    return 1;
#else
    std::cout << "Reflective ORM SQLite tests skipped\n";
    return 0;
#endif
}
