/**
 *
 *  @file orm_reflection_compile_fail.cc
 *  @author Leonardo Moreira
 *  @brief Negative compile tests for reflected ORM model diagnostics.
 *
 *  Copyright 2018, An Tao.  All rights reserved.
 *  https://github.com/drogonframework/drogon
 *  Use of this source code is governed by a MIT license
 *  that can be found in the License file.
 *
 */

#include <drogon/orm/ReflectiveMapper.h>

#include <cstddef>
#include <string>

namespace
{
namespace reflection = drogon::orm::reflection;

// clang-format currently treats reflection annotations as ordinary attributes.
// clang-format off
#if defined(DROGON_REFLECTION_FAIL_MISSING_TABLE)

struct InvalidModel
{
    [[=reflection::PrimaryKey{}]] int id;
};

#elif defined(DROGON_REFLECTION_FAIL_DUPLICATE_TABLE)

struct [[=reflection::Table{"first_table"},
         =reflection::Table{"second_table"}]] InvalidModel
{
    [[=reflection::PrimaryKey{}]] int id;
};

#elif defined(DROGON_REFLECTION_FAIL_MISSING_PRIMARY_KEY)

struct [[=reflection::Table{"missing_primary_key"}]] InvalidModel
{
    int id;
};

#elif defined(DROGON_REFLECTION_FAIL_DUPLICATE_PRIMARY_KEY)

struct [[=reflection::Table{"duplicate_primary_key"}]] InvalidModel
{
    [[=reflection::PrimaryKey{}]] int firstId;
    [[=reflection::PrimaryKey{}]] int secondId;
};

#elif defined(DROGON_REFLECTION_FAIL_INVALID_IDENTIFIER)

struct [[=reflection::Table{"invalid_identifier"}]] InvalidModel
{
    [[=reflection::PrimaryKey{}]] int id;
    [[=reflection::Column{"invalid-column"}]] int value;
};

#elif defined(DROGON_REFLECTION_FAIL_DUPLICATE_IDENTIFIER)

struct [[=reflection::Table{"duplicate_identifier"}]] InvalidModel
{
    [[=reflection::PrimaryKey{}, =reflection::Column{"duplicate"}]] int id;
    [[=reflection::Column{"duplicate"}]] int value;
};

#elif defined(DROGON_REFLECTION_FAIL_INCOMPATIBLE_IGNORE)

struct [[=reflection::Table{"incompatible_ignore"}]] InvalidModel
{
    [[=reflection::PrimaryKey{}]] int id;
    [[=reflection::Ignore{}, =reflection::Column{"ignored"}]] int value;
};

#elif defined(DROGON_REFLECTION_FAIL_AUTOGENERATED_NON_PRIMARY_KEY)

struct [[=reflection::Table{"generated_non_primary_key"}]] InvalidModel
{
    [[=reflection::PrimaryKey{}]] int id;
    [[=reflection::AutoGenerated{}]] int generatedValue;
};

#elif defined(DROGON_REFLECTION_FAIL_AUTOGENERATED_NON_INTEGRAL)

struct [[=reflection::Table{"generated_non_integral"}]] InvalidModel
{
    [[=reflection::PrimaryKey{}, =reflection::AutoGenerated{}]]
    std::string id;
};

#elif defined(DROGON_REFLECTION_FAIL_AUTOGENERATED_BOOL)

struct [[=reflection::Table{"generated_bool"}]] InvalidModel
{
    [[=reflection::PrimaryKey{}, =reflection::AutoGenerated{}]] bool id;
};

#elif defined(DROGON_REFLECTION_FAIL_CONST_MEMBER)

struct [[=reflection::Table{"const_member"}]] InvalidModel
{
    [[=reflection::PrimaryKey{}]] int id;
    const int value{};
};

#elif defined(DROGON_REFLECTION_FAIL_REFERENCE_MEMBER)

inline int referencedValue{};

struct [[=reflection::Table{"reference_member"}]] InvalidModel
{
    [[=reflection::PrimaryKey{}]] int id;
    int &value{referencedValue};
};

#elif defined(DROGON_REFLECTION_FAIL_BIT_FIELD)

struct [[=reflection::Table{"bit_field"}]] InvalidModel
{
    [[=reflection::PrimaryKey{}]] int id;
    unsigned int value : 1;
};

#elif defined(DROGON_REFLECTION_FAIL_INHERITANCE)

struct ModelBase
{
    int baseValue;
};

struct [[=reflection::Table{"inherited_model"}]] InvalidModel : ModelBase
{
    [[=reflection::PrimaryKey{}]] int id;
};

#elif defined(DROGON_REFLECTION_FAIL_INACCESSIBLE_MEMBER)

struct [[=reflection::Table{"inaccessible_member"}]] InvalidModel
{
    [[=reflection::PrimaryKey{}]] int id;

  private:
    int hidden;
};

#elif defined(DROGON_REFLECTION_FAIL_UNION)

union [[=reflection::Table{"union_model"}]] InvalidModel
{
    [[=reflection::PrimaryKey{}]] int id;
    int value;
};

#else
#error "A DROGON_REFLECTION_FAIL_* test case must be selected"
#endif
// clang-format on

static_assert(sizeof(drogon::orm::ReflectiveMapper<InvalidModel>) > 0);
}  // namespace

int main()
{
    return 0;
}
