//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class cmake:public drogon::DrTemplate<cmake>
{
public:
	cmake(){};
	virtual ~cmake(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
