//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class filter_cc:public drogon::DrTemplate<filter_cc>
{
public:
	filter_cc(){};
	virtual ~filter_cc(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
