//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class model_h:public drogon::DrTemplate<model_h>
{
public:
	model_h(){};
	virtual ~model_h(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
