//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class model_cc:public drogon::DrTemplate<model_cc>
{
public:
	model_cc(){};
	virtual ~model_cc(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
