//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class restful_controller_custom_cc:public drogon::DrTemplate<restful_controller_custom_cc>
{
public:
	restful_controller_custom_cc(){};
	virtual ~restful_controller_custom_cc(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
