// clang-format Language: Cpp

/**
 *
 *  @file ReflectiveMapper.h
 *  @author Leonardo Moreira
 *  @brief C++26 reflection based ORM mapper.
 *
 *  Copyright 2018, An Tao.  All rights reserved.
 *  https://github.com/drogonframework/drogon
 *  Use of this source code is governed by a MIT license
 *  that can be found in the License file.
 *
 */

#pragma once

#if !defined(__cpp_impl_reflection) || __cpp_impl_reflection < 202603L
#error "ReflectiveMapper requires C++26 reflection"
#else

#include <meta>

#if !defined(__cpp_lib_reflection) || __cpp_lib_reflection < 202603L || \
    !defined(__cpp_expansion_statements) ||                             \
    __cpp_expansion_statements < 202506L ||                             \
    !defined(__cpp_lib_define_static) || __cpp_lib_define_static < 202506L
#error \
    "ReflectiveMapper requires C++26 reflection, expansion statements, and define_static support"
#endif

#include <drogon/orm/Criteria.h>
#include <drogon/orm/DbClient.h>
#include <drogon/orm/Exception.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/SqlBinder.h>

#include <array>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <optional>
#include <string>
#include <string_view>
#include <type_traits>
#include <utility>
#include <vector>

// clang-format currently treats reflection annotations as ordinary attributes.
// clang-format off
namespace drogon
{
namespace orm
{
namespace reflection
{
/**
 * @brief A structural compile-time string used by ORM annotations.
 *
 * Annotation values must have structural types. A fixed buffer avoids storing
 * pointers to string literals, which cannot be extracted portably from an
 * annotation value.
 */
struct StaticString
{
    static constexpr std::size_t capacity = 256;

    std::array<char, capacity + 1> data{};
    std::size_t size{0};

    constexpr StaticString() = default;

    template <std::size_t N>
    consteval StaticString(const char (&value)[N])
    {
        assign(std::string_view(value, N - 1));
    }

    consteval void assign(std::string_view value)
    {
        if (value.size() > capacity)
        {
            throw "Reflective ORM identifier is longer than 256 characters";
        }
        size = value.size();
        for (std::size_t i = 0; i < size; ++i)
        {
            data[i] = value[i];
        }
        data[size] = '\0';
    }

    constexpr std::string_view view() const noexcept
    {
        return std::string_view(data.data(), size);
    }

    constexpr bool operator==(const StaticString &) const = default;
};

/// Associate an aggregate with a database table.
struct Table
{
    StaticString name;

    template <std::size_t N>
    consteval Table(const char (&value)[N]) : name(value)
    {
    }
};

/// Override the database column name of a data member.
struct Column
{
    StaticString name;

    template <std::size_t N>
    consteval Column(const char (&value)[N]) : name(value)
    {
    }
};

/// Mark the single primary-key member of a reflected model.
struct PrimaryKey
{
};

/// Mark an integral primary key whose value is generated by the database.
struct AutoGenerated
{
};

/// Exclude a data member from ORM mapping.
struct Ignore
{
};

namespace internal
{
enum class Dialect
{
    PostgreSQL,
    Mysql,
    Sqlite3
};

struct MemberMetadata
{
    StaticString columnName;
    bool primaryKey{false};
    bool autoGenerated{false};
    bool ignored{false};
};

constexpr bool isAsciiAlphaNumeric(char c) noexcept
{
    return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
           (c >= '0' && c <= '9');
}

consteval bool isValidIdentifier(std::string_view value,
                                 bool allowQualification)
{
    if (value.empty())
    {
        return false;
    }

    bool segmentHasCharacter = false;
    for (char c : value)
    {
        if (isAsciiAlphaNumeric(c) || c == '_')
        {
            segmentHasCharacter = true;
            continue;
        }
        if (allowQualification && c == '.' && segmentHasCharacter)
        {
            segmentHasCharacter = false;
            continue;
        }
        return false;
    }
    return segmentHasCharacter;
}

consteval StaticString staticStringFrom(std::string_view value)
{
    StaticString result;
    result.assign(value);
    return result;
}

template <typename T>
consteval auto membersOf()
{
    constexpr auto context = std::meta::access_context::current();
    return std::define_static_array(
        std::meta::nonstatic_data_members_of(^^T, context));
}

consteval MemberMetadata memberMetadataOf(std::meta::info member)
{
    const auto columns =
        std::meta::annotations_of_with_type(member, ^^Column);
    const auto primaryKeys =
        std::meta::annotations_of_with_type(member, ^^PrimaryKey);
    const auto generated =
        std::meta::annotations_of_with_type(member, ^^AutoGenerated);
    const auto ignored =
        std::meta::annotations_of_with_type(member, ^^Ignore);

    if (columns.size() > 1 || primaryKeys.size() > 1 ||
        generated.size() > 1 || ignored.size() > 1)
    {
        throw "Reflective ORM annotations must not be duplicated";
    }

    MemberMetadata result;
    result.primaryKey = primaryKeys.size() == 1;
    result.autoGenerated = generated.size() == 1;
    result.ignored = ignored.size() == 1;

    if (result.ignored &&
        (!columns.empty() || result.primaryKey || result.autoGenerated))
    {
        throw "Ignore cannot be combined with another ORM annotation";
    }

    if (!columns.empty())
    {
        result.columnName = std::meta::extract<Column>(columns.front()).name;
    }
    else
    {
        if (!std::meta::has_identifier(member))
        {
            throw "Every reflected ORM member must have an identifier";
        }
        result.columnName =
            staticStringFrom(std::meta::identifier_of(member));
    }
    return result;
}

template <std::meta::info Member>
inline constexpr MemberMetadata memberMetadata = memberMetadataOf(Member);

template <typename T>
consteval Table tableMetadataOf()
{
    const auto tables = std::meta::annotations_of_with_type(^^T, ^^Table);
    if (tables.size() != 1)
    {
        throw "A reflected ORM model requires exactly one Table annotation";
    }
    return std::meta::extract<Table>(tables.front());
}

template <typename T>
inline constexpr Table tableMetadata = tableMetadataOf<T>();

template <typename T>
struct OptionalTraits
{
    static constexpr bool isOptional = false;
    using ValueType = T;
};

template <typename T>
struct OptionalTraits<std::optional<T>>
{
    static constexpr bool isOptional = true;
    using ValueType = T;
};

template <typename T>
using RemoveCvRef = std::remove_cv_t<std::remove_reference_t<T>>;

template <typename T>
using OptionalValue = typename OptionalTraits<RemoveCvRef<T>>::ValueType;

template <typename T>
consteval void validateModel()
{
    static_assert(std::is_aggregate_v<T>,
                  "A reflected ORM model must be an aggregate");
    static_assert(!std::is_union_v<T>,
                  "A reflected ORM model must not be a union");
    static_assert(std::is_default_constructible_v<T>,
                  "A reflected ORM model must be default constructible");

    constexpr auto context = std::meta::access_context::current();
    if (std::meta::has_inaccessible_nonstatic_data_members(^^T, context))
    {
        throw "All reflected ORM model members must be public";
    }
    if (!std::meta::bases_of(^^T, context).empty())
    {
        throw "Reflected ORM models must not have base classes";
    }

    const auto table = tableMetadataOf<T>();
    if (!isValidIdentifier(table.name.view(), true))
    {
        throw "The reflected ORM table name is not a valid SQL identifier";
    }

    std::size_t primaryKeyCount = 0;
    std::size_t autoGeneratedCount = 0;

    template for (constexpr auto member : membersOf<T>())
    {
        constexpr auto metadata = memberMetadataOf(member);
        if constexpr (!metadata.ignored)
        {
            if (!std::meta::is_public(member))
            {
                throw "All reflected ORM model members must be public";
            }
            if (std::meta::is_bit_field(member))
            {
                throw "Bit-fields are not supported by ReflectiveMapper";
            }
            if (!isValidIdentifier(metadata.columnName.view(), false))
            {
                throw "A reflected ORM column name is not a valid SQL identifier";
            }

            using MemberType = typename[:std::meta::type_of(member):];
            if constexpr (std::is_const_v<std::remove_reference_t<MemberType>> ||
                          std::is_reference_v<MemberType>)
            {
                throw "Mapped ORM members must be mutable value types";
            }

            if constexpr (metadata.primaryKey)
            {
                ++primaryKeyCount;
            }
            if constexpr (metadata.autoGenerated)
            {
                ++autoGeneratedCount;
                if constexpr (!metadata.primaryKey ||
                              !std::is_integral_v<OptionalValue<MemberType>>)
                {
                    throw "AutoGenerated requires an integral PrimaryKey member";
                }
                if constexpr (std::is_same_v<
                                  std::remove_cv_t<OptionalValue<MemberType>>,
                                  bool>)
                {
                    throw "AutoGenerated does not support bool PrimaryKey members";
                }
            }
        }
    }

    if (primaryKeyCount != 1)
    {
        throw "A reflected ORM model requires exactly one PrimaryKey member";
    }
    if (autoGeneratedCount > 1)
    {
        throw "A reflected ORM model supports at most one AutoGenerated member";
    }

    const auto members = membersOf<T>();
    for (std::size_t i = 0; i < members.size(); ++i)
    {
        const auto left = memberMetadataOf(members[i]);
        if (left.ignored)
        {
            continue;
        }
        for (std::size_t j = i + 1; j < members.size(); ++j)
        {
            const auto right = memberMetadataOf(members[j]);
            if (!right.ignored && left.columnName == right.columnName)
            {
                throw "Reflected ORM column names must be unique";
            }
        }
    }
}

template <typename T>
inline constexpr bool validModel = []() consteval {
    validateModel<T>();
    return true;
}();

template <typename T>
consteval std::meta::info primaryKeyMemberOf()
{
    validateModel<T>();
    template for (constexpr auto member : membersOf<T>())
    {
        if constexpr (memberMetadataOf(member).primaryKey)
        {
            return member;
        }
    }
    throw "A reflected ORM model has no PrimaryKey member";
}

template <typename T>
consteval bool hasAutoGeneratedKey()
{
    return memberMetadataOf(primaryKeyMemberOf<T>()).autoGenerated;
}

template <typename T>
consteval std::size_t mappedColumnCount()
{
    std::size_t result = 0;
    template for (constexpr auto member : membersOf<T>())
    {
        if constexpr (!memberMetadataOf(member).ignored)
        {
            ++result;
        }
    }
    return result;
}

template <typename T>
consteval std::size_t insertColumnCount()
{
    std::size_t result = 0;
    template for (constexpr auto member : membersOf<T>())
    {
        constexpr auto metadata = memberMetadataOf(member);
        if constexpr (!metadata.ignored && !metadata.autoGenerated)
        {
            ++result;
        }
    }
    return result;
}

template <typename T>
consteval std::size_t updateColumnCount()
{
    std::size_t result = 0;
    template for (constexpr auto member : membersOf<T>())
    {
        constexpr auto metadata = memberMetadataOf(member);
        if constexpr (!metadata.ignored && !metadata.primaryKey &&
                      !metadata.autoGenerated)
        {
            ++result;
        }
    }
    return result;
}

template <Dialect D>
constexpr std::string quoteIdentifier(std::string_view identifier)
{
    constexpr char quote = D == Dialect::Mysql ? '`' : '"';
    std::string result;
    result.reserve(identifier.size() + 4);
    result.push_back(quote);
    for (char c : identifier)
    {
        if (c == '.')
        {
            result.push_back(quote);
            result.push_back('.');
            result.push_back(quote);
        }
        else
        {
            result.push_back(c);
        }
    }
    result.push_back(quote);
    return result;
}

template <Dialect D>
consteval std::string placeholder(std::size_t index)
{
    if constexpr (D == Dialect::PostgreSQL)
    {
        std::string result{"$"};
        char digits[20]{};
        std::size_t count = 0;
        do
        {
            digits[count++] = static_cast<char>('0' + index % 10);
            index /= 10;
        } while (index != 0);
        while (count != 0)
        {
            result.push_back(digits[--count]);
        }
        return result;
    }
    else
    {
        (void)index;
        return "?";
    }
}

template <typename T, Dialect D>
consteval void appendMappedColumns(std::string &sql)
{
    bool first = true;
    template for (constexpr auto member : membersOf<T>())
    {
        constexpr auto metadata = memberMetadataOf(member);
        if constexpr (!metadata.ignored)
        {
            if (!first)
            {
                sql.push_back(',');
            }
            first = false;
            sql += quoteIdentifier<D>(metadata.columnName.view());
        }
    }
}

template <typename T, Dialect D>
consteval std::string buildSelectSql()
{
    validateModel<T>();
    std::string sql = "select ";
    appendMappedColumns<T, D>(sql);
    sql += " from ";
    sql += quoteIdentifier<D>(tableMetadata<T>.name.view());
    return sql;
}

template <typename T, Dialect D>
consteval std::string buildFindByPrimaryKeySql()
{
    std::string sql = buildSelectSql<T, D>();
    constexpr auto key = memberMetadataOf(primaryKeyMemberOf<T>());
    sql += " where ";
    sql += quoteIdentifier<D>(key.columnName.view());
    sql += " = ";
    sql += placeholder<D>(1);
    return sql;
}

template <typename T, Dialect D>
consteval std::string buildCountSql()
{
    validateModel<T>();
    std::string sql = "select count(*) from ";
    sql += quoteIdentifier<D>(tableMetadata<T>.name.view());
    return sql;
}

template <typename T, Dialect D>
consteval std::string buildInsertSql()
{
    validateModel<T>();
    std::string sql = "insert into ";
    sql += quoteIdentifier<D>(tableMetadata<T>.name.view());

    if constexpr (insertColumnCount<T>() == 0)
    {
        if constexpr (D == Dialect::Mysql)
        {
            sql += " () values ()";
        }
        else
        {
            sql += " default values";
        }
    }
    else
    {
        sql += " (";
        bool first = true;
        template for (constexpr auto member : membersOf<T>())
        {
            constexpr auto metadata = memberMetadataOf(member);
            if constexpr (!metadata.ignored && !metadata.autoGenerated)
            {
                if (!first)
                {
                    sql.push_back(',');
                }
                first = false;
                sql += quoteIdentifier<D>(metadata.columnName.view());
            }
        }
        sql += ") values (";
        for (std::size_t i = 1; i <= insertColumnCount<T>(); ++i)
        {
            if (i > 1)
            {
                sql.push_back(',');
            }
            sql += placeholder<D>(i);
        }
        sql.push_back(')');
    }

    if constexpr (D == Dialect::PostgreSQL && hasAutoGeneratedKey<T>())
    {
        sql += " returning ";
        appendMappedColumns<T, D>(sql);
    }
    return sql;
}

template <typename T, Dialect D>
consteval std::string buildUpdateSql()
{
    validateModel<T>();
    std::string sql = "update ";
    sql += quoteIdentifier<D>(tableMetadata<T>.name.view());
    sql += " set ";
    std::size_t index = 1;
    bool first = true;
    template for (constexpr auto member : membersOf<T>())
    {
        constexpr auto metadata = memberMetadataOf(member);
        if constexpr (!metadata.ignored && !metadata.primaryKey &&
                      !metadata.autoGenerated)
        {
            if (!first)
            {
                sql.push_back(',');
            }
            first = false;
            sql += quoteIdentifier<D>(metadata.columnName.view());
            sql += " = ";
            sql += placeholder<D>(index++);
        }
    }
    constexpr auto key = memberMetadataOf(primaryKeyMemberOf<T>());
    sql += " where ";
    sql += quoteIdentifier<D>(key.columnName.view());
    sql += " = ";
    sql += placeholder<D>(index);
    return sql;
}

template <typename T, Dialect D>
consteval std::string buildDeleteSql()
{
    validateModel<T>();
    constexpr auto key = memberMetadataOf(primaryKeyMemberOf<T>());
    std::string sql = "delete from ";
    sql += quoteIdentifier<D>(tableMetadata<T>.name.view());
    sql += " where ";
    sql += quoteIdentifier<D>(key.columnName.view());
    sql += " = ";
    sql += placeholder<D>(1);
    return sql;
}

template <typename T, Dialect D>
inline constexpr const char *selectSql =
    std::define_static_string(buildSelectSql<T, D>());

template <typename T, Dialect D>
inline constexpr const char *findByPrimaryKeySql =
    std::define_static_string(buildFindByPrimaryKeySql<T, D>());

template <typename T, Dialect D>
inline constexpr const char *countSql =
    std::define_static_string(buildCountSql<T, D>());

template <typename T, Dialect D>
inline constexpr const char *insertSql =
    std::define_static_string(buildInsertSql<T, D>());

template <typename T, Dialect D>
inline constexpr const char *updateSql =
    std::define_static_string(buildUpdateSql<T, D>());

template <typename T, Dialect D>
inline constexpr const char *deleteSql =
    std::define_static_string(buildDeleteSql<T, D>());

template <typename T>
std::string_view selectSqlFor(ClientType type)
{
    switch (type)
    {
        case ClientType::PostgreSQL:
            return selectSql<T, Dialect::PostgreSQL>;
        case ClientType::Mysql:
            return selectSql<T, Dialect::Mysql>;
        case ClientType::Sqlite3:
            return selectSql<T, Dialect::Sqlite3>;
    }
    assert(false);
    return {};
}

template <typename T>
std::string_view findByPrimaryKeySqlFor(ClientType type)
{
    switch (type)
    {
        case ClientType::PostgreSQL:
            return findByPrimaryKeySql<T, Dialect::PostgreSQL>;
        case ClientType::Mysql:
            return findByPrimaryKeySql<T, Dialect::Mysql>;
        case ClientType::Sqlite3:
            return findByPrimaryKeySql<T, Dialect::Sqlite3>;
    }
    assert(false);
    return {};
}

template <typename T>
std::string_view countSqlFor(ClientType type)
{
    switch (type)
    {
        case ClientType::PostgreSQL:
            return countSql<T, Dialect::PostgreSQL>;
        case ClientType::Mysql:
            return countSql<T, Dialect::Mysql>;
        case ClientType::Sqlite3:
            return countSql<T, Dialect::Sqlite3>;
    }
    assert(false);
    return {};
}

template <typename T>
std::string_view insertSqlFor(ClientType type)
{
    switch (type)
    {
        case ClientType::PostgreSQL:
            return insertSql<T, Dialect::PostgreSQL>;
        case ClientType::Mysql:
            return insertSql<T, Dialect::Mysql>;
        case ClientType::Sqlite3:
            return insertSql<T, Dialect::Sqlite3>;
    }
    assert(false);
    return {};
}

template <typename T>
std::string_view updateSqlFor(ClientType type)
{
    switch (type)
    {
        case ClientType::PostgreSQL:
            return updateSql<T, Dialect::PostgreSQL>;
        case ClientType::Mysql:
            return updateSql<T, Dialect::Mysql>;
        case ClientType::Sqlite3:
            return updateSql<T, Dialect::Sqlite3>;
    }
    assert(false);
    return {};
}

template <typename T>
std::string_view deleteSqlFor(ClientType type)
{
    switch (type)
    {
        case ClientType::PostgreSQL:
            return deleteSql<T, Dialect::PostgreSQL>;
        case ClientType::Mysql:
            return deleteSql<T, Dialect::Mysql>;
        case ClientType::Sqlite3:
            return deleteSql<T, Dialect::Sqlite3>;
    }
    assert(false);
    return {};
}

inline std::string replaceCriteriaPlaceholders(std::string sql,
                                               ClientType type)
{
    std::size_t position = 0;
    std::size_t parameter = 1;
    while ((position = sql.find("$?", position)) != std::string::npos)
    {
        std::string replacement = "?";
        if (type == ClientType::PostgreSQL)
        {
            replacement = "$" + std::to_string(parameter++);
        }
        sql.replace(position, 2, replacement);
        position += replacement.size();
    }
    return sql;
}

template <typename T>
T fromRow(const Row &row)
{
    T object{};
    template for (constexpr auto member : membersOf<T>())
    {
        constexpr auto metadata = memberMetadataOf(member);
        if constexpr (!metadata.ignored)
        {
            using MemberType = RemoveCvRef<typename[:std::meta::type_of(member):]>;
            using Traits = OptionalTraits<MemberType>;
            using ValueType = typename Traits::ValueType;
            const std::string column(metadata.columnName.view());
            const auto field = row[column];

            try
            {
                if constexpr (Traits::isOptional)
                {
                    if (field.isNull())
                    {
                        object.[:member:].reset();
                    }
                    else
                    {
                        object.[:member:] = field.template as<ValueType>();
                    }
                }
                else
                {
                    if (field.isNull())
                    {
                        throw ConversionError("Column `" + column +
                                              "` is NULL but its reflected "
                                              "member is not std::optional");
                    }
                    object.[:member:] = field.template as<ValueType>();
                }
            }
            catch (const DrogonDbException &)
            {
                throw;
            }
            catch (const std::exception &error)
            {
                throw ConversionError("Could not convert column `" + column +
                                      "`: " + error.what());
            }
        }
    }
    return object;
}

template <typename T>
std::vector<T> fromResult(const Result &result)
{
    std::vector<T> objects;
    objects.reserve(result.size());
    for (const auto &row : result)
    {
        objects.push_back(fromRow<T>(row));
    }
    return objects;
}

template <typename T>
void bindInsert(const T &object, drogon::orm::internal::SqlBinder &binder)
{
    template for (constexpr auto member : membersOf<T>())
    {
        constexpr auto metadata = memberMetadataOf(member);
        if constexpr (!metadata.ignored && !metadata.autoGenerated)
        {
            binder << object.[:member:];
        }
    }
}

template <typename T>
void bindUpdate(const T &object, drogon::orm::internal::SqlBinder &binder)
{
    template for (constexpr auto member : membersOf<T>())
    {
        constexpr auto metadata = memberMetadataOf(member);
        if constexpr (!metadata.ignored && !metadata.primaryKey &&
                      !metadata.autoGenerated)
        {
            binder << object.[:member:];
        }
    }
}

template <typename T>
decltype(auto) objectPrimaryKey(const T &object)
{
    constexpr auto member = primaryKeyMemberOf<T>();
    using MemberType = RemoveCvRef<typename[:std::meta::type_of(member):]>;
    using Traits = OptionalTraits<MemberType>;

    if constexpr (Traits::isOptional)
    {
        if (!object.[:member:])
        {
            throw UsageError(
                "The reflected model's primary key does not have a value");
        }
        return *object.[:member:];
    }
    else
    {
        return (object.[:member:]);
    }
}

template <typename T>
void bindObjectPrimaryKey(const T &object,
                          drogon::orm::internal::SqlBinder &binder)
{
    binder << objectPrimaryKey(object);
}

template <typename T>
void assignGeneratedPrimaryKey(T &object, std::uint64_t value)
{
    if constexpr (hasAutoGeneratedKey<T>())
    {
        constexpr auto member = primaryKeyMemberOf<T>();
        using MemberType =
            RemoveCvRef<typename[:std::meta::type_of(member):]>;
        using Traits = OptionalTraits<MemberType>;
        using ValueType = typename Traits::ValueType;
        if (!std::in_range<ValueType>(value))
        {
            throw RangeError(
                "Generated primary key is outside the model member's range");
        }
        object.[:member:] = static_cast<ValueType>(value);
    }
    else
    {
        (void)object;
        (void)value;
    }
}

inline void validateSingleResult(const Result &result)
{
    if (result.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    if (result.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
}

template <typename Callback>
void invokeExceptionCallback(const Callback &callback,
                             const std::exception &exception)
{
    ConversionError error(exception.what());
    callback(error);
}

}  // namespace internal
}  // namespace reflection

/**
 * @brief Mapper for C++26 reflected aggregates.
 *
 * This mapper is intentionally independent from Mapper<T>. It provides a
 * code-first path while preserving all generated-model behavior.
 */
template <typename T>
class ReflectiveMapper
{
    static_assert(reflection::internal::validModel<T>);

    using PrimaryKeyMemberType = reflection::internal::RemoveCvRef<
        typename[:std::meta::type_of(
            reflection::internal::primaryKeyMemberOf<T>()):]>;

  public:
    using PrimaryKeyType =
        typename reflection::internal::OptionalTraits<
            PrimaryKeyMemberType>::ValueType;
    using SingleRowCallback = std::function<void(T)>;
    using MultipleRowsCallback = std::function<void(std::vector<T>)>;
    using CountCallback = std::function<void(std::size_t)>;

    explicit ReflectiveMapper(DbClientPtr client) : client_(std::move(client))
    {
        if (!client_)
        {
            throw ArgumentError("ReflectiveMapper requires a DbClient");
        }
    }

    /** Return a correctly quoted column identifier for the client's dialect. */
    template <std::meta::info Member>
    std::string columnName() const
    {
        static_assert(std::meta::is_nonstatic_data_member(Member),
                      "columnName requires a non-static data member");
        static_assert(std::meta::parent_of(Member) == ^^T,
                      "columnName member must belong to this model type");
        constexpr auto metadata =
            reflection::internal::memberMetadataOf(Member);
        static_assert(!metadata.ignored,
                      "Ignored members do not have ORM column names");

        switch (client_->type())
        {
            case ClientType::PostgreSQL:
                return reflection::internal::quoteIdentifier<
                    reflection::internal::Dialect::PostgreSQL>(
                    metadata.columnName.view());
            case ClientType::Mysql:
                return reflection::internal::quoteIdentifier<
                    reflection::internal::Dialect::Mysql>(
                    metadata.columnName.view());
            case ClientType::Sqlite3:
                return reflection::internal::quoteIdentifier<
                    reflection::internal::Dialect::Sqlite3>(
                    metadata.columnName.view());
        }
        assert(false);
        return {};
    }

    T findByPrimaryKey(const PrimaryKeyType &key) const
    {
        Result result(nullptr);
        auto binder = *client_ <<
                      reflection::internal::findByPrimaryKeySqlFor<T>(
                          client_->type());
        binder << key << Mode::Blocking;
        binder >> [&result](const Result &value) { result = value; };
        binder.exec();
        reflection::internal::validateSingleResult(result);
        return reflection::internal::fromRow<T>(result[0]);
    }

    void findByPrimaryKey(const PrimaryKeyType &key,
                          const SingleRowCallback &resultCallback,
                          const ExceptionCallback &exceptionCallback) const
        noexcept
    {
        try
        {
            auto binder = *client_ <<
                          reflection::internal::findByPrimaryKeySqlFor<T>(
                              client_->type());
            binder << key;
            binder >> [resultCallback, exceptionCallback](const Result &result) {
                try
                {
                    reflection::internal::validateSingleResult(result);
                    resultCallback(
                        reflection::internal::fromRow<T>(result[0]));
                }
                catch (const DrogonDbException &error)
                {
                    exceptionCallback(error);
                }
                catch (const std::exception &error)
                {
                    reflection::internal::invokeExceptionCallback(
                        exceptionCallback, error);
                }
            };
            binder >> exceptionCallback;
            binder.exec();
        }
        catch (const DrogonDbException &error)
        {
            exceptionCallback(error);
        }
        catch (const std::exception &error)
        {
            reflection::internal::invokeExceptionCallback(exceptionCallback,
                                                          error);
        }
    }

    T findOne(const Criteria &criteria) const
    {
        const auto result = executeFind(criteria);
        reflection::internal::validateSingleResult(result);
        return reflection::internal::fromRow<T>(result[0]);
    }

    void findOne(const Criteria &criteria,
                 const SingleRowCallback &resultCallback,
                 const ExceptionCallback &exceptionCallback) const noexcept
    {
        executeFind(
            criteria,
            [resultCallback, exceptionCallback](const Result &result) {
                try
                {
                    reflection::internal::validateSingleResult(result);
                    resultCallback(
                        reflection::internal::fromRow<T>(result[0]));
                }
                catch (const DrogonDbException &error)
                {
                    exceptionCallback(error);
                }
                catch (const std::exception &error)
                {
                    reflection::internal::invokeExceptionCallback(
                        exceptionCallback, error);
                }
            },
            exceptionCallback);
    }

    std::vector<T> findBy(const Criteria &criteria) const
    {
        return reflection::internal::fromResult<T>(executeFind(criteria));
    }

    void findBy(const Criteria &criteria,
                const MultipleRowsCallback &resultCallback,
                const ExceptionCallback &exceptionCallback) const noexcept
    {
        executeFind(
            criteria,
            [resultCallback, exceptionCallback](const Result &result) {
                try
                {
                    resultCallback(
                        reflection::internal::fromResult<T>(result));
                }
                catch (const DrogonDbException &error)
                {
                    exceptionCallback(error);
                }
                catch (const std::exception &error)
                {
                    reflection::internal::invokeExceptionCallback(
                        exceptionCallback, error);
                }
            },
            exceptionCallback);
    }

    std::vector<T> findAll() const
    {
        return findBy(Criteria());
    }

    void findAll(const MultipleRowsCallback &resultCallback,
                 const ExceptionCallback &exceptionCallback) const noexcept
    {
        findBy(Criteria(), resultCallback, exceptionCallback);
    }

    std::size_t count(const Criteria &criteria = Criteria()) const
    {
        Result result(nullptr);
        auto sql = countSql(criteria);
        auto binder = *client_ << std::move(sql);
        if (criteria)
        {
            criteria.outputArgs(binder);
        }
        binder << Mode::Blocking;
        binder >> [&result](const Result &value) { result = value; };
        binder.exec();
        if (result.size() != 1)
        {
            throw UnexpectedRows("Count query did not return exactly one row");
        }
        return result[0][0].as<std::size_t>();
    }

    void count(const Criteria &criteria,
               const CountCallback &resultCallback,
               const ExceptionCallback &exceptionCallback) const noexcept
    {
        try
        {
            auto sql = countSql(criteria);
            auto binder = *client_ << std::move(sql);
            if (criteria)
            {
                criteria.outputArgs(binder);
            }
            binder >> [resultCallback, exceptionCallback](const Result &result) {
                try
                {
                    if (result.size() != 1)
                    {
                        throw UnexpectedRows(
                            "Count query did not return exactly one row");
                    }
                    resultCallback(result[0][0].as<std::size_t>());
                }
                catch (const DrogonDbException &error)
                {
                    exceptionCallback(error);
                }
                catch (const std::exception &error)
                {
                    reflection::internal::invokeExceptionCallback(
                        exceptionCallback, error);
                }
            };
            binder >> exceptionCallback;
            binder.exec();
        }
        catch (const DrogonDbException &error)
        {
            exceptionCallback(error);
        }
        catch (const std::exception &error)
        {
            reflection::internal::invokeExceptionCallback(exceptionCallback,
                                                          error);
        }
    }

    void insert(T &object) const
    {
        Result result(nullptr);
        auto binder = *client_ <<
                      reflection::internal::insertSqlFor<T>(client_->type());
        reflection::internal::bindInsert(object, binder);
        binder << Mode::Blocking;
        binder >> [&result](const Result &value) { result = value; };
        binder.exec();
        if (result.affectedRows() != 1)
        {
            throw UnexpectedRows("Insert did not affect exactly one row");
        }
        applyInsertResult(object, result);
    }

    void insert(const T &object,
                const SingleRowCallback &resultCallback,
                const ExceptionCallback &exceptionCallback) const noexcept
    {
        try
        {
            auto binder = *client_ << reflection::internal::insertSqlFor<T>(
                              client_->type());
            reflection::internal::bindInsert(object, binder);
            const auto type = client_->type();
            binder >> [object = T(object),
                       type,
                       resultCallback,
                       exceptionCallback](const Result &result) mutable {
                try
                {
                    if (result.affectedRows() != 1)
                    {
                        throw UnexpectedRows(
                            "Insert did not affect exactly one row");
                    }
                    applyInsertResult(object, result, type);
                    resultCallback(std::move(object));
                }
                catch (const DrogonDbException &error)
                {
                    exceptionCallback(error);
                }
                catch (const std::exception &error)
                {
                    reflection::internal::invokeExceptionCallback(
                        exceptionCallback, error);
                }
            };
            binder >> exceptionCallback;
            binder.exec();
        }
        catch (const DrogonDbException &error)
        {
            exceptionCallback(error);
        }
        catch (const std::exception &error)
        {
            reflection::internal::invokeExceptionCallback(exceptionCallback,
                                                          error);
        }
    }

    std::size_t update(const T &object) const
    {
        (void)reflection::internal::objectPrimaryKey(object);
        if constexpr (reflection::internal::updateColumnCount<T>() == 0)
        {
            return 0;
        }
        Result result(nullptr);
        auto binder = *client_ <<
                      reflection::internal::updateSqlFor<T>(client_->type());
        reflection::internal::bindUpdate(object, binder);
        reflection::internal::bindObjectPrimaryKey(object, binder);
        binder << Mode::Blocking;
        binder >> [&result](const Result &value) { result = value; };
        binder.exec();
        return result.affectedRows();
    }

    void update(const T &object,
                const CountCallback &resultCallback,
                const ExceptionCallback &exceptionCallback) const noexcept
    {
        try
        {
            (void)reflection::internal::objectPrimaryKey(object);
            if constexpr (reflection::internal::updateColumnCount<T>() == 0)
            {
                resultCallback(0);
                return;
            }
            auto binder = *client_ << reflection::internal::updateSqlFor<T>(
                              client_->type());
            reflection::internal::bindUpdate(object, binder);
            reflection::internal::bindObjectPrimaryKey(object, binder);
            binder >> [resultCallback](const Result &result) {
                resultCallback(result.affectedRows());
            };
            binder >> exceptionCallback;
            binder.exec();
        }
        catch (const DrogonDbException &error)
        {
            exceptionCallback(error);
        }
        catch (const std::exception &error)
        {
            reflection::internal::invokeExceptionCallback(exceptionCallback,
                                                          error);
        }
    }

    std::size_t deleteOne(const T &object) const
    {
        Result result(nullptr);
        auto binder = *client_ <<
                      reflection::internal::deleteSqlFor<T>(client_->type());
        reflection::internal::bindObjectPrimaryKey(object, binder);
        binder << Mode::Blocking;
        binder >> [&result](const Result &value) { result = value; };
        binder.exec();
        return result.affectedRows();
    }

    void deleteOne(const T &object,
                   const CountCallback &resultCallback,
                   const ExceptionCallback &exceptionCallback) const noexcept
    {
        try
        {
            auto binder = *client_ << reflection::internal::deleteSqlFor<T>(
                              client_->type());
            reflection::internal::bindObjectPrimaryKey(object, binder);
            binder >> [resultCallback](const Result &result) {
                resultCallback(result.affectedRows());
            };
            binder >> exceptionCallback;
            binder.exec();
        }
        catch (const DrogonDbException &error)
        {
            exceptionCallback(error);
        }
        catch (const std::exception &error)
        {
            reflection::internal::invokeExceptionCallback(exceptionCallback,
                                                          error);
        }
    }

    std::size_t deleteByPrimaryKey(const PrimaryKeyType &key) const
    {
        Result result(nullptr);
        auto binder = *client_ <<
                      reflection::internal::deleteSqlFor<T>(client_->type());
        binder << key << Mode::Blocking;
        binder >> [&result](const Result &value) { result = value; };
        binder.exec();
        return result.affectedRows();
    }

    void deleteByPrimaryKey(
        const PrimaryKeyType &key,
        const CountCallback &resultCallback,
        const ExceptionCallback &exceptionCallback) const noexcept
    {
        try
        {
            auto binder = *client_ << reflection::internal::deleteSqlFor<T>(
                              client_->type());
            binder << key;
            binder >> [resultCallback](const Result &result) {
                resultCallback(result.affectedRows());
            };
            binder >> exceptionCallback;
            binder.exec();
        }
        catch (const DrogonDbException &error)
        {
            exceptionCallback(error);
        }
        catch (const std::exception &error)
        {
            reflection::internal::invokeExceptionCallback(exceptionCallback,
                                                          error);
        }
    }

  private:
    Result executeFind(const Criteria &criteria) const
    {
        Result result(nullptr);
        auto sql = findSql(criteria);
        auto binder = *client_ << std::move(sql);
        if (criteria)
        {
            criteria.outputArgs(binder);
        }
        binder << Mode::Blocking;
        binder >> [&result](const Result &value) { result = value; };
        binder.exec();
        return result;
    }

    void executeFind(const Criteria &criteria,
                     const ResultCallback &resultCallback,
                     const ExceptionCallback &exceptionCallback) const noexcept
    {
        try
        {
            auto sql = findSql(criteria);
            auto binder = *client_ << std::move(sql);
            if (criteria)
            {
                criteria.outputArgs(binder);
            }
            binder >> resultCallback;
            binder >> exceptionCallback;
            binder.exec();
        }
        catch (const DrogonDbException &error)
        {
            exceptionCallback(error);
        }
        catch (const std::exception &error)
        {
            reflection::internal::invokeExceptionCallback(exceptionCallback,
                                                          error);
        }
    }

    std::string findSql(const Criteria &criteria) const
    {
        std::string sql(
            reflection::internal::selectSqlFor<T>(client_->type()));
        if (criteria)
        {
            sql += " where ";
            sql += criteria.criteriaString();
            sql = reflection::internal::replaceCriteriaPlaceholders(
                std::move(sql), client_->type());
        }
        return sql;
    }

    std::string countSql(const Criteria &criteria) const
    {
        std::string sql(
            reflection::internal::countSqlFor<T>(client_->type()));
        if (criteria)
        {
            sql += " where ";
            sql += criteria.criteriaString();
            sql = reflection::internal::replaceCriteriaPlaceholders(
                std::move(sql), client_->type());
        }
        return sql;
    }

    void applyInsertResult(T &object, const Result &result) const
    {
        applyInsertResult(object, result, client_->type());
    }

    static void applyInsertResult(T &object,
                                  const Result &result,
                                  ClientType type)
    {
        if constexpr (reflection::internal::hasAutoGeneratedKey<T>())
        {
            if (type == ClientType::PostgreSQL)
            {
                reflection::internal::validateSingleResult(result);
                object = reflection::internal::fromRow<T>(result[0]);
            }
            else
            {
                reflection::internal::assignGeneratedPrimaryKey(
                    object, result.insertId());
            }
        }
    }

    DbClientPtr client_;
};

}  // namespace orm
}  // namespace drogon

// clang-format on

#endif
