//this file is generated by program automatically,don't modify it!
#include <drogon/HttpView.h>
using namespace drogon;
class NotFound:public HttpView<NotFound>
{
public:
	NotFound(){};
	virtual ~NotFound(){};
	protected:
				virtual HttpResponse* genHttpResponse(const HttpViewData&)override;
};