name: C++

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dos2unix
        run: sudo apt-get install -y dos2unix

      - name: Check formatting
        run: ./format.sh && git diff --exit-code
